### ISSUE TITLE
Azimuth Points Renaming

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#130]
right now, the dropdown in the project setup for Urbit Star backed funds denotes them as `Azimuth Points`. This has been a snag for every one of the urbit grantees in setting up their project. we should rename the dropdown to: `Urbit Stars (@AZP)`

**Comment by thelifeandtimes** [comment]
Also add a little "view token on etherscan" hyperlink on the project creation page to enable checking by project workers.

**Comment by sidnym-ladrut** [comment]
This was fixed in 1.4.0.
