### ISSUE TITLE
Following card additional details

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#131]
right now, the difference between a following card and a discover card doesn't take advantage of the live data or make for easy browsing of projects. I think the play here is to add a minified version of the thermometer or a color-coded dot for status? It's probably true that my initial designs tried to put too much on the card, but we may have oversimplified and swung the pendulum too far the other way.

**Comment by sidnym-ladrut** [comment]
I think this largely has been fixed by 1.4.X.

**Comment by thelifeandtimes** [comment]
Agreed, closing.
