### ISSUE TITLE
Search bar nitpicks

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#150]
- [ ] outer highlight on focus should be muted (this might be my browser; but can we take over that behavior? do we want to?)
- [ ] Button to search should be inside the search bar to indicate that it is a search, but when the cursor is active in the bar, it should be an arrow to submit. It should also trigger on hitting enter.
- [ ] slightly more left padding on the `search projects...` placeholder text / entry contents

**Comment by sidnym-ladrut** [comment]
Changing the search icon on focus turns out to be tricky with `alpine`. I worked on it for 30-45 minutes and couldn't find a solution, so I'm abandoning that feature for now. The other features are included in #163.

**Comment by thelifeandtimes** [comment]
sounds good. We can stash this for later.
