### ISSUE TITLE
Weird `?` tooltip on %work campaign

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#155]
Somehow, the share button is rendering within the `?` tooltip on ~polrel-witter's %work campaign:
![image](https://github.com/user-attachments/assets/cbc1a57f-4887-4340-85c7-a46758bc55bb)

It went away on refresh but flagging in the off chance we can get a repro. Doesn't seem to happen in any other campaigns...

**Comment by sidnym-ladrut** [comment]
I'm pretty sure this is a refresh-related thing; please re-open if you see it again.
