### ISSUE TITLE
Sort and Filter icons

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#159]
- [x] change color so they are visible
- [x] probably add some on-hover properties to indicate interaction opportunity
- [x] on desktop give them text labels. this will both make them more usable, and help fill in some of the open space between icons.
- [x] alphabetical arrow indicator doesn't change on toggle (`a` and `z` swap, arrow remains pointing down. in using this, the expected behavior is probably to have the arrow change directions, rather than the letters swap ordering?)

**Comment by sidnym-ladrut** [comment]
Fixed by #163
