### ISSUE TITLE
On-Click of different icon buttons

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#166]
In the dashboard bar, the on-click border of the icon buttons are rounded and a bit too constraining:
<img width="174" alt="image" src="https://github.com/user-attachments/assets/59ade237-2cd5-4b67-9f5c-58c6713dae44">

In the campaign page action bar the on-click border is not rounded and lightly conflicts with the on-hover behavior (a lighter background)
<img width="162" alt="image" src="https://github.com/user-attachments/assets/55bc960b-f1bd-4490-9e20-411a8c769991">

This also shows up in the account dropdown toggle: 
<img width="307" alt="image" src="https://github.com/user-attachments/assets/2fb13020-5539-48fe-bab6-f9d477eee878">

Expected behavior would be for these to all be the same, both in how much padding they give the interior icons, and in the rounded-ness of their corners.

**Comment by sidnym-ladrut** [comment]
Yeah I can fix these things. I can definitely fix the outlines; normalizing hover behavior for the project view icons is TBD.
