### ISSUE TITLE
Funding Tracker font contrast

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#167]
The contrast on the milestone text in the funding tracker is too low when the milestone has been fully funded:
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/464c0129-ac03-40ea-9b5c-210c8ce54593">

These don't need to be _high _contrast_, but should be a little bit more legible.

**Comment by thelifeandtimes** [comment]
Also, the % raised should be able to go >100%

**Comment by sidnym-ladrut** [comment]
This is happening because the text and thermometer colors are actually the same. @ahlmark: I'm going to make the "overfunded" the barber-shop striped color so we can see the milestone text.
