### ISSUE TITLE
Reconnect thread not succeeding

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#169]
I heave a few projects to which I pledged (~litneb's sticker pack, ~simfur's GDPR, ~nordbird's urbit videos) where the connection got severed somehow. The warning icon shows up on the following page, but when I go into the campaign pages the reconnect button errors out:
<img width="219" alt="image" src="https://github.com/user-attachments/assets/ccb2539b-eead-4906-bff2-334bcf26c54d">

I ran the %exit and %join pokes manually in the dojo for ~nordus' campaign and it seemed to properly reconnect so I'm not sure exactly what is going on here.

**Comment by sidnym-ladrut** [comment]
This will only work once the host has been updated to v1.4.4+. Unfortunately, I can't make this work "natively" with older versions because of annoying CORS stuff (at least in a robust way).

**Comment by sidnym-ladrut** [comment]
Alternatively to the current behavior that checks if the host is actually hosting the project at the same URL, we could just enable users to try to reconnect without checking if the host project is still online (would allow compatibility with older versions), but this would result in data loss if the host is offline.

**Comment by thelifeandtimes** [comment]
Ah. Probably fine to just leave and focus on getting everyone updated to 1.4.4+. Will close for now.
