### ISSUE TITLE
Milestone 1 - $WSTR Support

### ISSUE THREAD

**Issue by thelifeandtimes** [tocwex/fund#70]
As a first step into expanded currency support, we will update the urbit application side of %fund to support projects denominated in Wrapped Star ($WSTR). This will enable the Urbit Foundation grant proposers to self-publish their own grant proposals where both the Foundation and the community can put fractional address space behind the execution of urbit development projects.

**Comment by sidnym-ladrut** [comment]
@thelifeandtimes: I think this is completed; feel free to reopen if not.
